# Verificando kmeans punto 1.6


In [2]:
import numpy as np
import os
import pandas as pd
from scipy import stats
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import tarfile
import zipfile
from sklearn.cluster import AgglomerativeClustering
from scipy.io import loadmat
from urllib.request import urlretrieve
from os.path import isfile, isdir
from IPython.display import Image 
import plotly.figure_factory as ff
import plotly.express as px

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
%matplotlib inline


Leeremos el dataset 


In [3]:
df = pd.read_csv("data/VERIFICACIONKMEANS.csv")

In [4]:
df.describe()

X1         X2         X3
count  21.000000  21.000000  21.000000
mean    2.333333   4.428571  31.380952
std     1.527525   2.618615  18.180969
min     0.000000   0.000000   1.000000
25%     1.000000   3.000000  18.000000
50%     2.000000   4.000000  28.000000
75%     3.000000   6.000000  44.000000
max     5.000000   9.000000  64.000000

Aplicaremos el kmeans una vez leidos los datos

In [8]:
kmeans = KMeans(n_clusters=3,init='random', random_state=0,verbose=100).fit(df)

Initialization complete
Iteration 0, inertia 1376.0.
Iteration 1, inertia 1038.575.
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 9949.0.
Iteration 1, inertia 2102.531428571428.
Iteration 2, inertia 1165.2703703703703.
Iteration 3, inertia 989.1022727272727.
Converged at iteration 3: strict convergence.
Initialization complete
Iteration 0, inertia 2675.0.
Iteration 1, inertia 989.1022727272727.
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 1775.0.
Iteration 1, inertia 1110.35.
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 7236.0.
Iteration 1, inertia 1048.201388888889.
Iteration 2, inertia 861.4571428571429.
Converged at iteration 2: strict convergence.
Initialization complete
Iteration 0, inertia 2251.0.
Iteration 1, inertia 1102.4172222222223.
Iteration 2, inertia 1038.575.
Converged at iteration 2: strict convergence.
Initialization complete
Iteratio

C:\Users\Miguel Rios\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [9]:
kmeans.cluster_centers_

array([[ 1.        ,  2.2       , 16.        ],
       [ 4.5       ,  8.5       , 59.5       ],
       [ 3.        ,  5.28571429, 37.28571429]])

In [10]:
kmeans.labels_

array([2, 0, 2, 2, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 2, 1, 0, 0])

In [11]:
kmeans_4 = KMeans(n_clusters=4,init='random', random_state=0,verbose=100).fit(df)

Initialization complete
Iteration 0, inertia 986.0.
Iteration 1, inertia 708.4083333333334.
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 2418.0.
Iteration 1, inertia 743.6567145376669.
Iteration 2, inertia 708.4083333333334.
Converged at iteration 2: strict convergence.
Initialization complete
Iteration 0, inertia 1775.0.
Iteration 1, inertia 863.953125.
Iteration 2, inertia 708.4083333333334.
Converged at iteration 2: strict convergence.
Initialization complete
Iteration 0, inertia 1307.0.
Iteration 1, inertia 524.2922222222222.
Iteration 2, inertia 460.45.
Converged at iteration 2: strict convergence.
Initialization complete
Iteration 0, inertia 1407.0.
Iteration 1, inertia 542.2272727272726.
Iteration 2, inertia 410.97727272727275.
Converged at iteration 2: strict convergence.
Initialization complete
Iteration 0, inertia 1189.0.
Iteration 1, inertia 522.72.
Iteration 2, inertia 460.45.
Converged at iteration 2: strict convergence.
Initia

C:\Users\Miguel Rios\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [12]:
kmeans.cluster_centers_

array([[ 1.        ,  2.2       , 16.        ],
       [ 4.5       ,  8.5       , 59.5       ],
       [ 3.        ,  5.28571429, 37.28571429]])

In [13]:
kmeans.labels_

array([2, 0, 2, 2, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 2, 1, 0, 0])